name: graphcalculator

services:
  postgres:
    image: postgres:18.2-alpine3.23
    container_name: postgres
    env_file:
      - db/.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
      # postgres executes sql this dir on startup
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  nginx:
    image: nginx:1.29.5-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../packages/client/dist:/var/www/graphCalculator/dist
      - ../packages/server/public:/var/www/graphCalculator/public
volumes:
  pgdata:
